# Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [7]:
# Create a 1D array
arr1 = np.array([1,2,3,4])
print("1D Array", arr1)
arr1

1D Array [1 2 3 4]


array([1, 2, 3, 4])

In [6]:
# Create a 2D array
arr2 = np.array([[1,2],[3,4]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2]
 [3 4]]


In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Data Type: int64


In [12]:
# 1D Array

In [16]:
arr_1d = np.array([1,2,3,4])
print("1D Array:", arr_1d)
print("Shape:", arr_1d.shape)
print("Dimension:",arr_1d.ndim)
print("Data Type:", arr.dtype)

1D Array: [1 2 3 4]
Shape: (4,)
Dimension: 1
Data Type: int64


In [17]:
# 2D Array

In [19]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("1D Array:", arr_2d)
print("Shape:", arr_2d.shape)
print("Dimension:",arr_2d.ndim)
print("Data Type:", arr_2d.dtype)

1D Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Data Type: int64


In [24]:
# 3D array

In [26]:
arr_3d = np.array([[[1,2],[3,4],[5,6]]])
print("1D Array:", arr_3d)
print("Shape:", arr_3d.shape)
print("Dimension:",arr_3d.ndim)
print("Data Type:", arr_3d.dtype)

1D Array: [[[1 2]
  [3 4]
  [5 6]]]
Shape: (1, 3, 2)
Dimension: 3
Data Type: int64


In [ ]:
# Array creation

In [27]:
# array of zeros
zeros = np.zeros((2,3))
print("Zero:\n", zeros)

Zero:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# array of ones

ones = np.ones((2,3))
print("Zero:\n", ones)

Zero:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# range of values
range_arr = np.arange(0, 10, 2)
print("Range", range_arr)

Range [0 2 4 6 8]


In [32]:
# Array Operation

In [35]:
arr = np.array([1,2,3,4,5])
print("Original:", arr)
print("Add 5:", arr + 5)
print("Square:", arr ** 2)
print("Divide:", arr / 2)


Original: [1 2 3 4 5]
Add 5: [ 6  7  8  9 10]
Square: [ 1  4  9 16 25]
Divide: [0.5 1.  1.5 2.  2.5]


In [36]:
# Indexing and Slicing

In [41]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\2", arr_2d)
print("Element at [0,1]:", arr_2d[0,1])
print("First Row:", arr_2d[0,:])
print("Second Col:", arr_2d[:, 1])

2D Array: [[1 2 3]
 [4 5 6]]
Element at [0,1]: 2
First Row: [1 2 3]
Second Col: [2 5]


In [42]:
# Mathematical Functions

In [43]:
arr = np.array([1,2,3,4])
print("Array:", arr)
print("Sine:", np.sin(arr))
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

Array: [1 2 3 4]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Sum: 10
Mean: 2.5


In [ ]:
# Reshaping Array

In [45]:
arr = np.array([1,2,3,4,5,6])
print("Original:", arr)
reshaped = arr.reshape(2,3)
print("Reshape to 2x3:\n",reshaped)




Original: [1 2 3 4 5 6]
Reshape to 2x3:
 [[1 2 3]
 [4 5 6]]


In [47]:
arr_2d = np.array([[1,2,3],[4,5,6]])



arr_1d = arr_2d.reshape(6)
print("\nReshaped to 1D array", arr_1d)
print("Shaped:",arr_1d.shape)


Reshaped to 1D array [1 2 3 4 5 6]
Shaped: (6,)


In [50]:
arr_1d_flat = arr_1d.flatten()
print("Flattened:",arr_1d_flat)

Flattened: [1 2 3 4 5 6]
